name: Release

on:
  push:
    branches:
      - prePI

jobs:
  version:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Instalar dependências
        run: npm install

      - name: Rodar build
        run: npm run build

      # 🐳 DOCKER LOGIN
      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Testes unitarios
        run: npm test    

      # 🔍 SONAR CLOUD SCAN
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Checkout do código com token
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Instalar semver
        run: npm install -g semver

      - name: Criar nova tag caso não exista
        id: create_initial_tag
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [ -z "$(git tag)" ]; then
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git tag -a v0.0.0 -m "Initial release"
            git push origin v0.0.0
          fi

      - name: Calcular nova versão
        id: version
        run: |
          git fetch --tags
          LAST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          if [ -z "$LAST_TAG" ]; then
            LAST_TAG="v0.0.0"
          fi
          echo "Versão Atual: $LAST_TAG"
          
          if [ "$LAST_TAG" = "v0.0.0" ]; then
            COMMITS=$(git log --pretty=format:"%s")
          else
            COMMITS=$(git log ${LAST_TAG}..HEAD --pretty=format:"%s")
          fi
          
          MAJOR=0
          MINOR=0
          PATCH=0
          
          for COMMIT in "$COMMITS"; do
            if [[ "$COMMIT" == *"BREAKING CHANGE"* ]]; then
              MAJOR=1
            elif [[ "$COMMIT" == *"feat"* ]]; then
              MINOR=1
            elif [[ "$COMMIT" == *"fix"* ]]; then
              PATCH=1
            fi
          done
          
          CURRENT_VERSION=${LAST_TAG#v}
          NEW_VERSION=$CURRENT_VERSION
          if [[ $MAJOR -eq 1 ]]; then
            NEW_VERSION=$(semver -i major $CURRENT_VERSION)
          elif [[ $MINOR -eq 1 ]]; then
            NEW_VERSION=$(semver -i minor $CURRENT_VERSION)
          elif [[ $PATCH -eq 1 ]]; then
            NEW_VERSION=$(semver -i patch $CURRENT_VERSION)
          fi
          
          echo "Nova versão: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Atualizar versão no package.json
        run: |
         CURRENT_VERSION=$(node -p "require('./package.json').version")
    
          if [ "$CURRENT_VERSION" = "${{ env.new_version }}" ]; then
            echo "Versão já está atual. Pulando atualização."
          else
          npm version ${{ env.new_version }} --no-git-tag-version
          fi  

          
      - name: Commit e push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add package.json
          
          # Só faz commit se houver mudanças no package.json
          if git diff --cached --quiet; then
            echo "Sem mudanças para commitar."
          else
            git commit -m "chore(release): version ${{ env.new_version }}"
          fi

          # Só cria a tag se ela não existir
          if git rev-parse v${{ env.new_version }} >/dev/null 2>&1; then
            echo "Tag v${{ env.new_version }} já existe."
          else
            git tag v${{ env.new_version }}
          fi
          
          git push origin prePI --tags

      # 🐳 DOCKER BUILD & PUSH
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/notagest-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/notagest-backend:v${{ env.new_version }}

      - name: Enviar e-mail de falha
        uses: dawidd6/action-send-mail@v3
        if: failure()
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_ORIGEM }}
          password: ${{ secrets.SENHA_EMAIL }}
          subject: Falha no Pipeline - ${{ github.repository }}
          to: ${{ secrets.EMAIL_DESTINO }}
          from: ${{ secrets.EMAIL_ORIGEM }}
